### PR TITLE
fix: Query planner partially evaluates a lambda body

### LINKED ISSUE #1192: Produce better error message when query plan is impossible
For example, given the condition `P.attr.permissions.folder.read.exists(f, R.attr.folder_path.contains(f))`, it's impossible to generate a query plan without knowing the value of `R.attr.folder_path`. This results in the following error message which is not very helpful.

```
error evaluating condition \"P.attr.permissions.folder.read.exists(f, R.attr.folder_path.contains(f))\": no such attribute: id: 4, attributes: [0xc000f2ad20 0xc000f2acc0 0xc000f2ac60]
```

### PR DESCRIPTION
**Pull request by dbuduev**
Fixes #1192

### CODE REVIEW

File: internal/engine/planner.go [hunk 1]
```diff
@@ -569,17 +569,19 @@ func evalComprehensionBody(env *cel.Env, pvars interpreter.PartialActivation, e
 		}
 		updateIds(le)
 		ast := cel.ParsedExprToAst(&exprpb.ParsedExpr{Expr: le})
-		partialVars, err := cel.PartialVars(pvars, cel.AttributePattern(ce.IterVar))
+
+		unknowns := append(pvars.UnknownAttributePatterns(), cel.AttributePattern(ce.IterVar))
```
Comment (haines) [inline internal/engine/planner.go:573]: If I'm reading above correctly, we don't allow just any unknown variable, it should just be `request.resource` or `R`, right? I think the same should apply here - if you introduce a random `x` that should be an error, but accessing a resource attribute should return an AST.

Comment (dbuduev) [reply internal/engine/planner.go:573]: Short version: Lambda parameter `x` is unknown in the context of lambda body evaluation. For example, `P.roles.exists(x, x.startsWith("admin"))`. Inside the inner expression `x.startsWith("admin")` the `x` is unknown.

Longer version:
When `evalComprehensionBody` is invoked the first time, the `pvars` contains `R`, `request`, `request.resource` in the unknowns list. In this code block, `ce` is a comprehension expression. 
For example `ce = P.roles.exists(x, x.startsWith("admin"))`, `le = x.startsWith("admin")`, `ce.IterVar = x`. In other words. `ce` is lambda, `x` is a lambda parameter, `le` is a lambda body.
We evaluate the lambda body here, so we must add `x` to the list of unknowns.

Comment (haines) [reply internal/engine/planner.go:573]: Thanks, I was confused about the purpose of `pvars.UnknownAttributePatterns()` but it makes sense now 🙂

**Review by haines — APPROVED** [review]
