### PR TITLE
fix: Evict policies from cache after disable or enable

### LINKED ISSUE #1710: Disabled/enabled policies stays in the cache until the store is reloaded
If a policy is disabled/enabled using `DisablePolicy`, `EnablePolicy` it stays in the cache until the store is reloaded.

### PR DESCRIPTION
**Pull request by oguzhand95**
- Fixes the problem with `Disable` and `Enable`. (resolves #1710)

### CODE REVIEW

File: internal/compile/manager.go [hunk 1]
```diff
@@ -93,7 +93,7 @@ func (c *Manager) processUpdateQueue(ctx context.Context) {
 			case storage.EventReload:
 				c.log.Info("Purging compile cache")
 				c.cache.Purge()
-			case storage.EventAddOrUpdatePolicy, storage.EventDeletePolicy:
+			case storage.EventAddOrUpdatePolicy, storage.EventDeleteDisableOrEnablePolicy:
```
Comment (charithe) [inline internal/compile/manager.go:96]: It should be just `EventDeleteOrDisablePolicy`. Enabling a policy works differently. I think that's covered by `AddOrUpdatePolicy`.
