### PR TITLE
chore(tooling): Fix confdocs not being able to parse examples consisting of an array

### LINKED ISSUE #1638: Confdocs can't parse array examples correctly
Given this configuration: 

```go
Compression []string `yaml:"compression" conf:",example=['zstd', 'snappy', 'none']"`
```

The parser stops at the first comma and produces an incomplete example.

```asciidoc
compression: ['zstd' # Compression sets the compression algorithm to use in order of priority. Valid values are "none", "gzip", "snappy","lz4", "zstd". Default is ["snappy", "none"].
```

### PR DESCRIPTION
**Pull request by oguzhand95**
Parsing logic from `structtag` doesn't have a way to configure whether we want to ignore a `,` character inside of square brackets while splitting the tag value such as;
```
Compression []string `conf:",example=['zstd', 'snappy', 'none']"`
```
This makes us unable to parse array examples such as: `['zstd', 'snappy', 'none']`

One possible solution to this was copying the implementation (or maybe we should fork it?) from `structtag` and modifying it to use [go-andiamo/splitter](github.com/go-andiamo/splitter), which I did for this PR.

fixes #1638

### CODE REVIEW

File: internal/audit/kafka/conf.go [hunk 1]
```diff
@@ -55,7 +55,7 @@ type Conf struct {
 	// Brokers list to seed the Kafka client.
 	Brokers []string `yaml:"brokers" conf:"required,example=['localhost:9092']"`
 	// Compression sets the compression algorithm to use in order of priority. Valid values are "none", "gzip", "snappy","lz4", "zstd". Default is ["snappy", "none"].
-	Compression []string `yaml:"compression" conf:",example=['snappy']"`
+	Compression []string `yaml:"compression" conf:",example=['zstd', 'snappy', 'none']"`
```
Comment (charithe) [inline internal/audit/kafka/conf.go:58]: If the default is `['snappy', 'none']`, let's set the example value to that as well.
```suggestion
	Compression []string `yaml:"compression" conf:",example=['snappy', 'none']"`
```

File: hack/tools/confdocs/confdocs.go [hunk 2]
```diff
@@ -542,3 +543,122 @@ func doInitLogging(level string) {
 
 	logger = l.Sugar()
 }
+
+var (
```
Comment (charithe) [inline hack/tools/confdocs/confdocs.go:547]: Let's put the code extracted from `structtag` into its own file and include the copyright notice from https://github.com/fatih/structtag/blob/master/LICENSE.

**Review by charithe — APPROVED** [review]
