### PR TITLE
fix(planner): Known resource attribute as an index into a struct

### LINKED ISSUE #1340: The query planner fails if a known resource attribute is an index into a struct
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

```yaml
apiVersion: api.cerbos.dev/v1
variables: 
  location_roles: P.attr.roles[R.attr.location_id]
derivedRoles:
  name: my_roles
  definitions:
    - name: global_admin
      parentRoles:
        - user
      condition:
        match:
          expr: ("Global Admin" in V.location_roles)
```

Log:
```
{"log.level":"info","@timestamp":"2022-11-07T23:34:00.201Z","log.logger":"cerbos.payload","message":"server request payload logged as grpc.request.content field","system":"grpc","span.kind":"server","grpc.service":"cerbos.svc.v1.CerbosService","grpc.method":"PlanResources","peer.address":"127.0.0.1:52082","http":{"x_forwarded_for":["172.17.0.1"],"x_forwarded_host":["localhost:3592"]},"grpc.request.content":{"msg":{"action":"entry:read","principal":{"id":"1","policyVersion":"default","roles":["user"],"attr":{"employee_id":"123","permissions":{"1":["entry.read_all"]},"roles":{"1":["Employee"]}}},"resource":{"kind":"entry","attr":{"location_id":"1"},"policyVersion":"default"},"includeMeta":true}}}
{"log.level":"error","@timestamp":"2022-11-07T23:34:00.203Z","log.logger":"cerbos.grpc","message":"Resources query plan request failed","grpc.start_time":"2022-11-07T23:34:00Z","system":"grpc","span.kind":"server","grpc.service":"cerbos.svc.v1.CerbosService","grpc.method":"PlanResources","peer.address":"127.0.0.1:52082","http":{"x_forwarded_for":["172.17.0.1"],"x_forwarded_host":["localhost:3592"]},"cerbos":{"call_id":"01GHA734RAWRPKZD2E4NGASBH1"},"error":"error evaluating condition \"(\\\"Employee\\\" in V.location_roles)\": invalid qualifier type: *structpb.Value"}
{"log.level":"error","@timestamp":"2022-11-07T23:34:00.203Z","log.logger":"cerbos.grpc","message":"Handled request","grpc.start_time":"2022-11-07T23:34:00Z","system":"grpc","span.kind":"server","grpc.service":"cerbos.svc.v1.CerbosService","grpc.method":"PlanResources","cerbos":{"call_id":"01GHA734RAWRPKZD2E4NGASBH1"},"peer.address":"127.0.0.1:52082","http":{"x_forwarded_for":["172.17.0.1"],"x_forwarded_host":["localhost:3592"]},"error":"rpc error: code = Internal desc = Resources query plan request failed","grpc.code":"Internal","grpc.time_ms":2.047}
```

### PR DESCRIPTION
**Pull request by dbuduev**
Signed-off-by: Dennis Buduev <dennis@cerbos.dev>

Fixes #1340

### CODE REVIEW

File: internal/engine/planner/planner.go [hunk 1]
```diff
@@ -538,6 +544,10 @@ func (p *partialEvaluator) evalPartially(e *exprpb.Expr) (ref.Val, *exprpb.Expr,
 func newEvaluator(input *enginev1.PlanResourcesInput) (p *partialEvaluator, err error) {
 	p = new(partialEvaluator)
 	knownVars := make(map[string]any)
+	knownVars[conditions.CELRequestIdent] = input
```
Comment (charithe) [inline internal/engine/planner/planner.go:547]: I am probably not understanding this correctly. Is it correct to say `request` is equal to the `PlanResourcesInput`? Normally `request` is `engine.CheckInput`, isn't it?

Comment (dbuduev) [reply internal/engine/planner/planner.go:547]: Yes and yes. This code path belongs exclusively to the query planner API. In this case `input` is `enginev1.PlanResourcesInput` as per https://github.com/cerbos/cerbos/blob/main/internal/svc/cerbos_svc.go#L60.

**Review by charithe — APPROVED** [review]
LGTM
