### PR TITLE
fix: Cerbosctl version should fail gracefully

### LINKED ISSUE #971: Cerbosctl version should fail gracefully
Running `cerbosctl version` fails when server credentials are not provided. This is because it tries to connect to Cerbos to get the remote version. When credentials are not provided or when the remote service is not accessible, it should still print the local version of `cerbosctl` instead of failing completely.

### PR DESCRIPTION
**Pull request by oguzhand95**
Signed-off-by: Oğuzhan Durgun <oguzhandurgun95@gmail.com>

#### Description

Fixes #971

### CODE REVIEW

File: cmd/cerbosctl/version/version.go [hunk 1]
```diff
@@ -16,14 +16,19 @@ import (
...
-	_, err = fmt.Fprintf(k.Stdout, "Client version %s; commit sha: %s, build date: %s\n", util.Version, util.Commit, util.BuildDate)
+	r, err := ctx.Client.ServerInfo(context.Background())
 	if err != nil {
-		return err
+		_, errPrint := fmt.Fprintf(k.Stdout, "Server version unknown; commit sha: unknown, build date: unknown\n")
+		if errPrint != nil {
+			return errPrint
+		}
+
+		return fmt.Errorf("failed to retrieve version, commit sha and build date from server: %w", err)
```
Comment (charithe) [inline cmd/cerbosctl/version/version.go:31]:
```suggestion
		return fmt.Errorf("failed to retrieve version information from the server: %w", err)
```

**Review by charithe — APPROVED** [review]
👍🏽
