### PR TITLE
fix: Ignore empty files in policy repository

### LINKED ISSUE #1880: Repeated compilation errors
If you attempt to compile an empty file, this is what you get

```
file is not valid: [/: expected object, but got null, /: expected object, but got null, /: expected object, but got null, /: expected object, but got null, /: expected object, but got null]
```

The `/: expected object, but got null` is repeated 4 times for some reason 🤔

### LINKED ISSUE #1883: Inconsistent YAML parsing between schema validation and policy loading
We use github.com/ghodss/yaml (which uses gopkg.in/yaml.v2 under the hood) to convert YAML to JSON for policy parsing but gopkg.in/yaml.v3 to parse YAML for schema validation.

That means that the following policy passes schema validation but then cannot be loaded:

```yaml
apiVersion: api.cerbos.dev/v1
resourcePolicy:
  resource: foo
  version: yes
```

The error should be `file is not valid: [/resourcePolicy/version: expected string, but got boolean]`, but instead we get `failed to unmarshal JSON: proto: (line 1:80): invalid value for string type: true`.

We should use the same YAML parser in both places.

### PR DESCRIPTION
**Pull request by charithe**
- Ignore empty files or files with commented out contents when building the index.
- Use the same YAML library for reading policies and validating them

Fixes #1880
Fixes #1883

Signed-off-by: Charith Ellawala <charith@cerbos.dev>

### CODE REVIEW

**Review by haines — APPROVED** [review]

**Comment by haines** [comment]
Actually, I think ignoring empty files is insufficient; I think we need to de-dupe the validation errors. For example, this YAML file

```yaml
wat
```

produces this error

```
file is not valid: [/: expected object, but got string, /: expected object, but got string, /: expected object, but got string, /: expected object, but got string, /: expected object, but got string]
```

File: internal/jsonschema/jsonschema.go [hunk 1]
```diff
@@ -74,68 +74,56 @@ func validate(s *jsonschema.Schema, fsys fs.FS, path string) error {
...
-
-type validationError struct {
-	Path    string
-	Message string
-}
-
-func (e validationError) Error() string {
-	return fmt.Sprintf("%s: %s", e.Path, e.Message)
-}
+	// sort the leaves by path and message, group by path and take the first message for each path to produce a stable set of errors
```
Comment (haines) [inline internal/jsonschema/jsonschema.go:104]: I think we should include all unique messages for each path rather than just the first. If there are multiple properties missing, for example, it would be nicer to be able to see that instead of playing whack-a-mole by adding the missing one we have reported and then getting a new error next time you compile.

Comment (charithe) [reply internal/jsonschema/jsonschema.go:104]: That's what I tried to do originally but, unfortunately, the error messages are not very good. You get whoppers like `additionalProperties 'key' not allowed, missing properties: 'apiVersion', missing properties: 'derivedRoles', missing properties: 'exportVariables', missing properties: 'principalPolicy', missing properties: 'resourcePolicy'`. 

I think it'd be quite rare to have multiple errors for a given path. We still report the errors for all  distinct paths so the user has a chance to fix all the errors at once in most cases anyway.

Comment (haines) [reply internal/jsonschema/jsonschema.go:104]: It's pretty common in the playground to have multiple missing properties as you work on a policy.

Also, I think this example shows an issue: https://github.com/cerbos/cerbos/pull/1882/files#diff-1f26e131097220eb6929f987c1065dbae423d87e53ca85d4ac4e5bfb7e67bbc3

The message would be `missing properties: 'derivedRoles', missing properties: 'exportVariables', missing properties: 'principalPolicy', missing properties: 'resourcePolicy'` but we chop it down to `missing properties: 'derivedRoles'` which is sort of untrue - you could add any of the four types... and you definitely can get into this state easily in the playground because the autocompleter will happily add the `apiVersion` for you but doesn't then suggest any of the `oneof` options.

**Review by haines — APPROVED** [review]
