### PR TITLE
chore(test): Fix Kafka integration tests

### LINKED ISSUE #1875: Kafka integration test is flaky
Probably needs a retry or a longer timeout

```
=== FAIL: internal/audit/kafka TestCompression (67.75s)
    kafka_test.go:133: 
        	Error Trace:	/home/runner/work/cerbos/cerbos/internal/audit/kafka/kafka_test.go:315
        	            				/home/runner/work/cerbos/cerbos/internal/audit/kafka/kafka_test.go:133
        	Error:      	Received unexpected error:
        	            	unable to dial: dial tcp [::1]:33765: connect: connection refused
        	Test:       	TestCompression
        	Messages:   	Failed to connect to Kafka

=== FAIL: internal/audit/kafka TestAsyncProduce (70.72s)
    kafka_test.go:[174](https://github.com/cerbos/cerbos/actions/runs/6847918721/job/18617098982?pr=1871#step:5:175): 
        	Error Trace:	/home/runner/work/cerbos/cerbos/internal/audit/kafka/kafka_test.go:315
        	            				/home/runner/work/cerbos/cerbos/internal/audit/kafka/kafka_test.go:174
        	Error:      	Received unexpected error:
        	            	reached retry deadline: unable to dial: dial tcp [::1]:35593: connect: connection refused
        	Test:       	TestAsyncProduce
        	Messages:   	Failed to connect to Kafka

=== FAIL: internal/audit/kafka TestProduceWithTLS (72.36s)
    kafka_test.go:43: 
        	Error Trace:	/home/runner/work/cerbos/cerbos/internal/audit/kafka/kafka_test.go:265
        	            				/home/runner/work/cerbos/cerbos/internal/audit/kafka/kafka_test.go:43
        	Error:      	Received unexpected error:
        	            	reached retry deadline: unable to dial: dial tcp [::1]:65136: connect: connection refused
        	Test:       	TestProduceWithTLS
        	Messages:   	Failed to connect to Kafka
```

### PR DESCRIPTION
**Pull request by charithe**
Kafka tests have been flaky lately and it seems to be due to two factors:
- Redpanda RPK tries to create a temporary configuration file in the same location as the `redpanda.yaml` file. If we mount a volume containing `redpanda.yaml` this fails because the `redpanda` user (uid 101) doesn't have permission to chmod. 
- A manifestation of https://github.com/moby/moby/issues/42442

This PR includes some refactoring to:
- Skip the RPK and start redpanda directly using a templated config file
- Combine the Kafka launch configuration to avoid repetition
- Output the Kafka container logs if `CERBOS_DEBUG_KAFKA` is set

Fixes #1875

Signed-off-by: Charith Ellawala <charith@cerbos.dev>

### CODE REVIEW

File: internal/audit/kafka/kafka_test.go [hunk 1]
```diff
@@ -24,31 +27,37 @@ import (
...
 
 	defaultIntegrationTopic = "cerbos"
+	maxWait                 = 60 * time.Second
 )
 
 func TestProduceWithTLS(t *testing.T) {
+	// Redpanda tries to create a temporary configuration file in /etc/redpanda (or whichever directory specified by --config)
+	// When that directory is a docker mount, the temp file creation fails because the Redpanda process is running as a user who
+	// doesn't have enough privileges to do so.
+	// t.Skip("TLS cannot be tested on Docker due to https://github.com/redpanda-data/redpanda/issues/12717")
```
Comment (haines) [inline internal/audit/kafka/kafka_test.go:46]: Is this outdated now?

File: internal/audit/kafka/kafka_test.go [hunk 2]
```diff
@@ -211,116 +220,138 @@ func TestAsyncProduce(t *testing.T) {
...
 
-	hostPort, err := util.GetFreePort()
-	require.NoError(t, err, "Unable to get free port")
+	/*
+		hostPort, err := util.GetFreeListenAddr()
+		require.NoError(t, err, "Failed to find free address")
+
+		host, port, err := net.SplitHostPort(hostPort)
+		require.NoError(t, err, "Failed to split free address: %s", hostPort)
+	*/
```
Comment (haines) [inline internal/audit/kafka/kafka_test.go:249]: Should this be removed?

**Review by haines — APPROVED** [review]
