### PR TITLE
enhancement: Handle schemas folder being in wrong place with more verbose error

### LINKED ISSUE #1539: Provide more verbose error message if `_schemas` directory is not at storage root
As per #1536

### PR DESCRIPTION
**Pull request by oguzhand95**
resolves #1539

### CODE REVIEW

File: internal/storage/index/builder.go [hunk 1]
```diff
@@ -94,6 +98,9 @@ func build(ctx context.Context, fsys fs.FS, opts buildOptions) (Index, error) {
 				d.Name() == util.TestDataDirectory ||
 				util.IsHidden(d.Name()) {
 				return fs.SkipDir
+			} else if strings.HasSuffix(filePath, schema.Directory) {
```
Comment (charithe) [inline internal/storage/index/builder.go:101]:
```suggestion
			} else if d.Name() == schema.Directory {
```

File: internal/storage/index/builder.go [hunk 2]
```diff
@@ -23,6 +24,9 @@ import (
 	"github.com/cerbos/cerbos/internal/util"
 )
 
+// ErrSchemasInWrongDir signals that schemas folder is in the wrong place.
+var ErrSchemasInWrongDir = fmt.Errorf("%s directory must be under the root of the storage directory", util.SchemasDirectory)
```
Comment (charithe) [inline internal/storage/index/builder.go:28]: This doesn't need to be a public error because we don't check for it anywhere.

File: internal/storage/index/builder.go (hunk 1 above)
Comment (haines) [inline internal/storage/index/builder.go:101]: Why `HasSuffix`? Wouldn't that potentially have false positives like `foo/bar_schemas`? What about 
```suggestion
			} else if d.Name() == schema.Directory {
```

**Review by charithe — APPROVED** [review]
