### PR TITLE
enhancement!: Group test results by test name

### LINKED ISSUE #1411: Test output mode where results are grouped by test name first
Follows from #1403

We currently don't display the name of the test case in the output produced by the test runner. It would be useful to have that information displayed to help users link the results back to a particular test case they wrote. 

One way to do this would be to group the results by test name first. However, if the JSON output also has to change to accommodate this (I haven't checked), then that would be a breaking change. In that case, let's evaluate whether we should go ahead with that breaking change or come up with an alternative.

### LINKED ISSUE #1490: Duplicate test detection false positive
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I get the following message when I have a duplicate test but with different input auxData.

```
  └──Duplicate test: The combination [acme_ny_plugin|acme_ny_entry_1|create] in test "Plugin Read Scopes Test" was already exercised in test "Plugin Tenancy Test"
```

### Expected Behavior

The test is not duplicate b/c the auxData jwt I'm passing in is different so it should not trigger the duplicate detection.

### Steps To Reproduce

LMK if you need this, happy to provide but I think its pretty self explanatory.

### Environment

```markdown
- OS: N/A
- Cerbos version: 0.25.0
- Docker version: N/A
- Go version: N/A
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by oguzhand95**
resolves #1411 
fixes #1490

### CODE REVIEW

File: internal/verify/test_fixture.go [hunk 1]
```diff
@@ -142,19 +142,21 @@ func (tf *testFixture) runTestSuite(ctx context.Context, eng Checker, shouldRun
 		}
 
 		for _, action := range test.Input.Actions {
-			testKey := fmt.Sprintf("%s|%s|%s", test.Name.PrincipalKey, test.Name.ResourceKey, action)
+			testKey := fmt.Sprintf("%s|%s|%s|%s", test.Name.TestTableName, test.Name.PrincipalKey, test.Name.ResourceKey, action)
```
Comment (charithe) [inline internal/verify/test_fixture.go:145]: We don't need to include the principal, resource and action here anymore. This check was added because of #1403. Because now the results are grouped by test name, that problem goes away. We only need to check that the test name is not duplicated.

File: internal/verify/verify_test.go [hunk 2]
```diff
@@ -42,6 +42,12 @@ type TestCase struct {
 	want    *policyv1.TestResults
 }
 
+func TestReloadGolden(t *testing.T) {
+	testCases := test.LoadTestCases(t, filepath.Join("verify", "cases"))
+	eng := mkEngine(t)
+	updateGoldenFiles(t, eng, testCases)
+}
```
Comment (charithe) [inline internal/verify/verify_test.go:49]: I don't think this is needed? Just run `go test -v -tags=tests ./internal/verify/... --args -updateGolden` to update the golden files.

File: api/public/cerbos/policy/v1/policy.proto [hunk 3]
```diff
@@ -291,11 +291,16 @@ message TestResults {
   message Suite {
     string file = 1;
     string name = 2;
-    repeated Principal principals = 3;
+    repeated TestCase test_cases = 3;
```
Comment (charithe) [inline api/public/cerbos/policy/v1/policy.proto:294]: I think we should keep the previous `principals` field at number 3 and mark it as deprecated. That way we don't break the old versions horribly (i.e. there won't be a parsing error). They would just see an empty principal list.

**Review by charithe — COMMENTED** [review]
I think we should add a test for #1490

File: internal/verify/test_fixture.go (hunk 1 above)
Comment (oguzhand95) [reply internal/verify/test_fixture.go:145]: Given a test file like this;
```yaml
tests:
  - name: Test 1
    input:
      principals:
        - admin
        - user
      resources:
        - contact
      actions:
        - create

    expected:
      - principal: admin
        resource: contact
        actions:
          create: EFFECT_ALLOW
      - principal: user
        resource: contact
        actions:
          create: EFFECT_ALLOW
```
We have two tests (separated into two: one with principal `admin`, another one with `user`) having the same test name (`Test 1`). Since both have the `Test 1` name after separation, I didn't remove the logic.

Comment (charithe) [reply internal/verify/test_fixture.go:145]: I see. In that case, the error message would look a bit strange because `testKey` already contains the test name in it. Maybe strip out the test name prefix from the `testKey` when producing the error message.

File: internal/test/testdata/verify/cases/case_010.yaml.input [hunk 4]
```diff
@@ -0,0 +1,59 @@
...
+    expected:
+      - principal: john
+        resource: john_leave_request
+        actions:
+          view:public: EFFECT_ALLOW
+
+  - name: Test 1
+    input:
+      principals:
+        - john
```
Comment (charithe) [inline internal/test/testdata/verify/cases/case_010.yaml.input:50]: If we change the principal here to someone else, would it still be detected as a duplicate test? We should probably disallow two test cases to have the same name regardless of whether they exercise completely different principals/resources/actions.

**Review by charithe — COMMENTED** [review]
LGTM but I think we need to check for duplicate test case names and warn the user as well.

File: internal/test/testdata/verify/cases/case_010.yaml.input (hunk 4 above)
Comment (oguzhand95) [reply internal/test/testdata/verify/cases/case_010.yaml.input:50]: I modified the relevant part. Now, we;
- continue even if we have the same `principal|resource|action` pair in two test cases. (`case_08`)
- continue even if we have the same `principal|resource|action` pair with different aux data. (`case_09`)
- fail the test if there are any duplicate test names present. (`case_10`)

Does this sound good?

**Review by charithe — APPROVED** [review]
LGTM
